name: flipcard
description: "A modern learning companion for effective memorization."
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  forui: ^0.13.1
  forui_assets: ^0.13.0
  flutter_launcher_icons: ^0.14.4
  flutter_secure_storage: ^9.2.4
  back_button_interceptor: ^8.0.4
  fluttertoast: ^8.2.12
  flutter_dotenv: ^5.2.1
  provider: ^6.1.5
  file_picker: ^10.2.0
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  supabase_flutter: ^2.9.1
  google_sign_in: ^6.1.5
  uuid: ^4.5.1
  flutter_svg: ^2.2.0
  speech_to_text: ^7.1.0
  permission_handler: ^12.0.1
  flutter_fullscreen: ^1.2.0
  flutter_tts: ^4.2.3
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  flutter_confetti: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
    - assets/images/
    - assets/svg/
    - assets/sounds/speech_to_text_listening.m4r
    - assets/sounds/speech_to_text_cancel.m4r
    - assets/sounds/speech_to_text_stop.m4r
  uses-material-design: true
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"